### ISSUE TITLE
Im getting an error while trying to run it.

### ISSUE THREAD

**Issue by HeinzRudi** [Bob-Rust/Bob-Rust-Java#1]
![2021-10-31 21_01_32-Bob-Rust-Java-0 0 1 Release](https://user-images.githubusercontent.com/61279986/139600115-d849a648-9985-47ed-8af8-23a88e9b4887.png)

**Comment by Kariaro** [comment]
This project requires that you have Java 16 installed. What is your current java version?

**Comment by HeinzRudi** [comment]
Yeah thanks that was the problem now it working fine thanks.
