### ISSUE TITLE
"Could not find the color palette" error

### ISSUE THREAD

**Issue by HeCorr** [Bob-Rust/Bob-Rust-Java#13]
Rust recently changed the painting UI (added undo and redo buttons).. Maybe that's the issue..?

Also yes, I am trying to paint a sign on a sign.  xD

Version: 0.0.2

![image](https://user-images.githubusercontent.com/75134774/148660116-e6ade533-b509-4cd2-bcdb-056ff08a07a9.png)

These are my settings:

![image](https://user-images.githubusercontent.com/75134774/148660118-f056f1f1-bb11-47e7-9946-9df40e67d871.png)

**Comment by Kariaro** [comment]
In one version of the tool it could only find the color palette the game was on the primary monitor.

I checked with my debug version if the screenshot works and it worked.

I will push a new version soon that might fix this.

**Comment by HeCorr** [comment]
I can confirm that I am using two monitors.

But what defines the primary monitor? Windows' primary monitor setting?

Because the game was running on my primary monitor as set in Windows.

Thanks!

**Comment by Kariaro** [comment]
I'm currently trying to update the tool so that it works.
Give me 10 mins and I will have the new version probably done.
I already had the patches but never pushed the code.


Or maybe primary monitor is the wrong word.
The monitor that windows login screen is show on.. That's the display it will work on.

**Comment by HeCorr** [comment]
> The monitor that the windows login screen usually displays on.

It's the correct one then. But anyway, thanks for looking into it!

> Give me 10 mins and I will have the new version probably done.

Take your time  :)

**Comment by HeCorr** [comment]
Oh, and another issue I noticed (which you might already be aware of) is that it doesn't detect when the generator has finished, forcing me to click "Pause generation" in order to start drawing.

I can create a separate issue for that if you haven't noticed/fixed it for the next release.  :)

**Comment by Kariaro** [comment]
https://github.com/Bob-Rust/Bob-Rust-Java/releases/tag/v0.1.45

Hopefully this release will fix your issues.

**Comment by HeCorr** [comment]
Awesome. Thanks!

I'll try it out soon  :)

**Comment by HeCorr** [comment]
It's unfortunately still not working  :(

![image](https://user-images.githubusercontent.com/75134774/149410874-6d249dbf-d99c-42fa-ba21-8ccfcefcd2be.png)

**Comment by HeCorr** [comment]
Btw.. just some extra info if relevant.. My main monitor is actually on the right, and my secondary at the left.

**Comment by Kariaro** [comment]
What is your monitors resolution? Maybe there is some scaling issue.

**Comment by HeCorr** [comment]
1920x1080, 125% scale

**Comment by Kariaro** [comment]
That's the issue thanks! Good thing we found it.

This means that if the scale of the screen is not 100% it wont detect the color palette.

If you try the application with 100% scale it should work.

**Comment by HeCorr** [comment]
I suggest you implement a way of having the user select the palette area themselves if automatic detection doesn't work.

And yeah, right after you asked me the resolution I looked at the scaling and knew it had to be it hahah

I'll be trying at 100% in a bit.

**Comment by Kariaro** [comment]
The scaling could maybe also break the painting process so I might have to debug a lot of stuff to get that working. I don't think the fix would be as easy as selecting the color palette.

**Comment by HeCorr** [comment]
Makes sense. At least we figured it out!

It works!  😄

![image](https://user-images.githubusercontent.com/75134774/149417188-f4074a40-cabb-4858-b9fb-55fa8f26562d.png)
